### PR TITLE
KMeans via JNI

### PR DESCRIPTION
**Pull request by mathemage**
a pull request studying how to run kmeans from Intel DAAL via Java (JNI)

### CODE REVIEW

**Comment by RuslanIsrafilov** [comment]
Hi @mathemage, thank you for notes, we will include it as a part of [FAQ](https://github.com/01org/daal/blob/daal_2018_beta_update1/FAQ.md).

**Comment by mathemage** [comment]
Thank you @RuslanIsrafilov . I am making them for my current project at H2O.ai, so it's more of an internal thing for H2O.ai. But do feel free to use anything for your FAQ. There were some interesting things to fix in order to make it run. And please bear in mind it's still work in progress. Thanks ^_^

**Comment by RuslanIsrafilov** [comment]
@mathemage, we updated [FAQ](https://github.com/01org/daal/blob/daal_2018/FAQ.md) and added a section about JNI based on your remarks.
> And please bear in mind it's still work in progress.

Are you planning to continue pushing commits or we can close this PR?

**Comment by mathemage** [comment]
Thanks, @RuslanIsrafilov ! Yes, you may close this PR, I won't add any more commits!

**Pull request closed without merging**
